### ISSUE TITLE
Перенос настройки root folder в базу

### ISSUE THREAD

**Issue by kadnikov** [kadnikov/jooq-doc#5]
Перенос настройки root folder в базу
Нужно определить настройку в базе, которая будет определять структуру хранения (аналог Storage Area в FN)

**Comment by ilya-ushakov** [comment]
Была добавлена запись в documents с параметрами
sys_type - storage_area.
data - {"maxsize": "1024", "repository": "/opt/doccloud/data"}.
Теперь данные ькпуися отсюда
