### ISSUE TITLE
Хранение файлов в иерархии автоматически создаваемых папок.

### ISSUE THREAD

**Issue by kadnikov** [kadnikov/jooq-doc#6]
Организовать структуру в файловой системе для хранения файлов приложенных к документам.

**Comment by ilya-ushakov** [comment]
В настоящий момент, файлы сохраня.тся следующим образом:
1. Сохраняется в базе документ. его uuid передается на вход метода writeFile()  сервиса fileActionsService.
2. Для двухуровневой структуры папок uuid разбивается пополам.
Первая часть используется для созлания папки первого уровня, вторая часть - для созлания вложенной папки.
3. Перед созданием папки проверяется существует ли уже на файорвой системе папка с таким именем (первая часть uuid).
3.1 если да, то вложенная папка будет создана, если такой нет. Если вложенная папка существует. то документ булет сохранен в ней.
3.2 если нет система создаст папку с именем  (первая часть uuid) и, после того, в ней де будет создана папка второго уровня.
4. в созданной структуре папок будет сохранен фвйл с имененм = uuid.
5. путь с созданному документу будет возвращен методом writeContent() и, после этого, будет добавлен в бд в соответствующее поле документа.
6. В соучае возникновения Exception ничего записано не будет. Будет возвпащено сообщение об ошибке.
