### ISSUE TITLE
Единая схема работы с файловой системой и связи файла с документом.

### ISSUE THREAD

**Issue by kadnikov** [kadnikov/jooq-doc#8]
Единая схема работы с файловой системой и связи файла с документом.

**Comment by ilya-ushakov** [comment]
1. в модуле docmanagement был реализован сервис fileActionsService.
public String writeFile(final UUID uuid, final byte[] fileArr) throws Exception;
    public byte[] readFile(final String filePath) throws Exception;
2.  в том же модуле был реализован репозиторий FileREpository
 public String writeFile(final UUID uuid, final byte[] fileArr) throws Exception;
    public byte[] readFile(final String filePath) throws Exception;
сохраняющий фвйлы на диск и читающий файл по заданному пути.
3. FileREpository используется сервисом fileActionsService.
4. FileActionsService используется
4.1. DocumentController
4.2. CMIS модулем.
5. модуль cmis был переработан для использования DocumentCrudService вместо DocumentRepository и FileActionsService.
6. для того чтобы методы контроллера были недоступны мз cmis модуля. Все контроллеры были вынесены из модуля documentmanagement в модуль   doccontrollers
